version: '3'
services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: always
    hostname: php
    volumes:
      - ./:/var/www/html
      - ./docker/var/run:/var/run/
      - ./docker/var/log:/var/log/
    depends_on:
      - rabbitmq
      - redis
      - mysql

  nginx:
    image: nginx:1.19.0-alpine
    restart: always
    hostname: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/nginx/default-prod.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl
      - ./docker/nginx/certbot/conf:/etc/letsencrypt
      - ./docker/nginx/certbot/www:/var/www/letsencrypt
      - ./:/var/www/html
      - ./docker/var/run:/var/run/
      - ./docker/var/log:/var/log/
    depends_on:
      - php

  certbot:
    image: certbot/certbot
    volumes:
      - ./docker/nginx/certbot/conf:/etc/letsencrypt
      - ./docker/nginx/certbot/www:/var/www/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  rabbitmq:
    image: rabbitmq:3.6.10-management
    hostname: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./docker/var/log:/var/log/
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASSWORD}"

  mysql:
    image: mysql
    restart: always
    hostname: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/var/data/mysql:/var/lib/mysql
      - ./docker/var/log/:/var/log/

  redis:
    image: redis
    restart: always
    hostname: redis
    command: redis-server
    ports:
      - 6379:6379

  worker:
    build:
      context: ./docker/worker
      dockerfile: Dockerfile
    restart: always
    hostname: worker
    volumes:
      - ./:/var/www/html
    depends_on:
      - rabbitmq

  composer:
    image: composer/composer
    container_name: composer
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    command: install

  frontend:
    image: node
    container_name: frontend
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    command: npm install
