FROM rabbitmq

ENV RABBITMQ_USER ${RABBITMQ_USER}
ENV RABBITMQ_PASSWORD ${RABBITMQ_USER}
ENV RABBITMQ_PID_FILE /var/lib/rabbitmq/mnesia/rabbitmq

ADD rabbit-init.sh /rabbit-init.sh
RUN chmod +x /rabbit-init.sh
EXPOSE 15672

CMD ["/rabbit-init.sh"]
